tags:
  - Project
summary: "Liste tout les projets"
produces:
  - "application/json"
definitions:
  Project:
    type: object
    properties:
      id_project:
        type: integer
      name:
        type: string
      description:
        type: string
      deadline:
        type: datetime
      size:
        type: integer
responses:
  200:
    description: "OK"
    schema:
      type: array
      items:
        $ref: '#/definitions/Project'
  404:
    description: "Not Found"
#    schema:
#      type: "object"
#      properties:
#        error:
#          type: "string"
#          example: "No project found"
  500:
    description: "Internal Server Error"
